---
name: PR Testing

on:
  pull_request: {}
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  pr-testing:
    name: PR Testing
    strategy:
      fail-fast: false
      matrix:
        version: ['17', '21', '25']
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          submodules: recursive
      - name: setup java
        uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.version }}
      - name: Install Clojure tools
        uses: DeLaGuardo/setup-clojure@4c7a6f613e5089821bb3bb2a33a3ee115578580d # 13.6.1
        with:
          lein: latest
          clj-kondo: latest
      - name: kondo lint
        run: clj-kondo --lint src test
      - name: eastwood lint
        run: |
          java -version
          lein eastwood
      - name: clojure tests
        run: lein test
        timeout-minutes: 30

  tests:
    if: always()
    needs:
      - pr-testing
    runs-on: ubuntu-24.04
    name: Test suite
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
